title = "Configuration File"

[webserver]
listen_address = "0.0.0.0"
listen_port = 8080
access_url = "http://127.0.0.1:8080"

[misc]
app_secret = "DxweajRJSIfygOj3DxmQOehJwcV1qZz8TSghpWzTfmZSTkWxn9VF2hY9"

[logging]
log_file = "logs/log"
log_level = "debug"
create_directory = true

[database.sqlite3]
enabled = true
file_path = "db.sqlite3"

[database.sqlServer]
enabled = false
server = "127.0.0.1"
port = 3006
db_name = "myDB"
db_user = "root"
db_password = "password"
db_type = "mysql"
